// src/lib/gameItems.js

// =====================================================================================
// FIREPILOT CATALOG
// Compatibility-first version:
// - Keeps current gameplay weapons working exactly as expected
// - Keeps current upgrade ids used by GameCanvas
// - Adds expanded catalog for future Armory tabs:
//   Weapons, Specials, Upgrades, Combo Packs, Vehicles
// =====================================================================================

// ───────────────────────────────────────────────────────────────────────────────
// WEAPONS
// Keep the currently-playable weapon ids and fields intact because GameCanvas
// already depends on them.
// ───────────────────────────────────────────────────────────────────────────────

export const WEAPONS = [
  // ===== CURRENT LIVE / CORE WEAPONS =====
  {
    id: 'blaster',
    name: 'BLASTER',
    desc: 'Standard rapid-fire laser. Reliable. Classic.',
    emoji: '🔫',
    rarity: 'starter',
    tier: 'starter',
    category: 'weapon',
    cost: 0,
    usd: 0,
    color: '#ffff00',
    fireRate: 12,
    type: 'single',
    live: true,
  },
  {
    id: 'blaster2',
    name: 'TWIN BURST',
    desc: '2-round burst. Twice the punch, twice the style.',
    emoji: '🔥',
    rarity: 'common',
    tier: 'common',
    category: 'weapon',
    cost: 500,
    usd: 9.99,
    color: '#ff8800',
    fireRate: 14,
    type: 'burst',
    burstCount: 2,
    live: true,
  },
  {
    id: 'rocket',
    name: 'ROCKET MK-III',
    desc: 'Burst + 2 heat-seeking rockets under the belly. Very powerful.',
    emoji: '🚀',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'weapon',
    cost: 1000,
    usd: 19.99,
    color: '#ff4400',
    fireRate: 16,
    type: 'rocket',
    burstCount: 2,
    live: true,
  },
  {
    id: 'auto',
    name: 'FULL AUTO',
    desc: 'Fully automatic. Hold and destroy.',
    emoji: '⚡',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'weapon',
    cost: 1200,
    usd: 19.99,
    color: '#00ffff',
    fireRate: 5,
    type: 'auto',
    live: true,
  },
  {
    id: 'lightning',
    name: 'LIGHTNING ZAP',
    desc: 'Zaps nearby enemies. When charge is low, it falls back to auto-fire.',
    emoji: '☇',
    rarity: 'elite',
    tier: 'elite',
    category: 'weapon',
    cost: 1500,
    usd: 24.99,
    color: '#ffffff',
    fireRate: 8,
    type: 'lightning',
    maxCharge: 180,
    rechargeRate: 1,
    drainRate: 20,
    zapRadius: 140,
    chainCount: 3,
    damage: 2,
    live: true,
  },

  // ===== NEW CATALOG / NOT YET WIRED TO GAMEPLAY =====
  {
    id: 'pulse_rifle',
    name: 'PULSE RIFLE',
    desc: 'Fast pulse fire with clean rhythm and consistent damage.',
    emoji: '🔫',
    rarity: 'common',
    tier: 'common',
    category: 'weapon',
    cost: 500,
    usd: 9.99,
    color: '#7df9ff',
    type: 'future',
    live: false,
  },
  {
    id: 'flak_shotgun',
    name: 'FLAK SHOTGUN',
    desc: 'Wide burst spread for close-range destruction.',
    emoji: '💥',
    rarity: 'common',
    tier: 'common',
    category: 'weapon',
    cost: 500,
    usd: 9.99,
    color: '#ffcc66',
    type: 'future',
    live: false,
  },
  {
    id: 'flame_thrower',
    name: 'FLAME THROWER',
    desc: 'Short-range stream weapon that melts crowded lanes.',
    emoji: '🔥',
    rarity: 'common',
    tier: 'common',
    category: 'weapon',
    cost: 500,
    usd: 9.99,
    color: '#ff6600',
    type: 'future',
    live: false,
  },
  {
    id: 'ricochet_blaster',
    name: 'RICOCHET BLASTER',
    desc: 'Projectiles bounce and keep pressure on the screen.',
    emoji: '🪩',
    rarity: 'rare',
    tier: 'rare',
    category: 'weapon',
    cost: 600,
    usd: 11.99,
    color: '#66ccff',
    type: 'future',
    live: false,
  },
  {
    id: 'emp_launcher',
    name: 'EMP LAUNCHER',
    desc: 'Disruptive burst weapon designed to shut down threats.',
    emoji: '🌀',
    rarity: 'rare',
    tier: 'rare',
    category: 'weapon',
    cost: 600,
    usd: 11.99,
    color: '#99ddff',
    type: 'future',
    live: false,
  },
  {
    id: 'cluster_bomb_launcher',
    name: 'CLUSTER BOMB LAUNCHER',
    desc: 'Explosive payload splits into secondary blasts.',
    emoji: '💣',
    rarity: 'rare',
    tier: 'rare',
    category: 'weapon',
    cost: 600,
    usd: 11.99,
    color: '#ff9966',
    type: 'future',
    live: false,
  },
  {
    id: 'plasma_lance',
    name: 'PLASMA LANCE',
    desc: 'Focused high-energy beam weapon.',
    emoji: '🟦',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'weapon',
    cost: 700,
    usd: 13.99,
    color: '#66ffff',
    type: 'future',
    live: false,
  },
  {
    id: 'napalm_rockets',
    name: 'NAPALM ROCKETS',
    desc: 'Incendiary rocket payloads with lingering burn.',
    emoji: '🚀',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'weapon',
    cost: 700,
    usd: 13.99,
    color: '#ff5533',
    type: 'future',
    live: false,
  },
  {
    id: 'seismic_cannon',
    name: 'SEISMIC CANNON',
    desc: 'Heavy impact weapon with strong lane-clearing potential.',
    emoji: '🌋',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'weapon',
    cost: 1200,
    usd: 19.99,
    color: '#ffaa44',
    type: 'future',
    live: false,
  },
  {
    id: 'chain_explosion_gun',
    name: 'CHAIN EXPLOSION GUN',
    desc: 'Explosions trigger secondary explosive chains.',
    emoji: '⛓️',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'weapon',
    cost: 1100,
    usd: 18.99,
    color: '#ff8899',
    type: 'future',
    live: false,
  },
  {
    id: 'swarm_drones',
    name: 'SWARM DRONES',
    desc: 'Deploy autonomous attack drones to harass targets.',
    emoji: '🛸',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'weapon',
    cost: 1200,
    usd: 19.99,
    color: '#88ffcc',
    type: 'future',
    live: false,
  },
  {
    id: 'auto_turrets',
    name: 'AUTO TURRETS',
    desc: 'Support turrets that provide sustained area fire.',
    emoji: '🗼',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'weapon',
    cost: 1100,
    usd: 18.99,
    color: '#99ffff',
    type: 'future',
    live: false,
  },
  {
    id: 'ion_storm',
    name: 'ION STORM',
    desc: 'Storm-class electric saturation weapon.',
    emoji: '⚡',
    rarity: 'elite',
    tier: 'elite',
    category: 'weapon',
    cost: 1200,
    usd: 19.99,
    color: '#c8f7ff',
    type: 'future',
    live: false,
  },
  {
    id: 'quantum_splitter',
    name: 'QUANTUM SPLITTER',
    desc: 'Projectiles split into unstable quantum fragments.',
    emoji: '🧬',
    rarity: 'elite',
    tier: 'elite',
    category: 'weapon',
    cost: 1300,
    usd: 21.99,
    color: '#cc99ff',
    type: 'future',
    live: false,
  },
  {
    id: 'gravity_well_gun',
    name: 'GRAVITY WELL GUN',
    desc: 'Pulls threats inward and distorts space around impacts.',
    emoji: '🕳️',
    rarity: 'elite',
    tier: 'elite',
    category: 'weapon',
    cost: 1200,
    usd: 19.99,
    color: '#8899ff',
    type: 'future',
    live: false,
  },
  {
    id: 'mirror_gun',
    name: 'MIRROR GUN',
    desc: 'Reflective weapon system that duplicates fire patterns.',
    emoji: '🪞',
    rarity: 'elite',
    tier: 'elite',
    category: 'weapon',
    cost: 1300,
    usd: 21.99,
    color: '#ddddff',
    type: 'future',
    live: false,
  },
  {
    id: 'orbiting_orbs',
    name: 'ORBITING ORBS',
    desc: 'Defensive/offensive orbitals that damage nearby enemies.',
    emoji: '🪐',
    rarity: 'elite',
    tier: 'elite',
    category: 'weapon',
    cost: 1100,
    usd: 18.99,
    color: '#99ccff',
    type: 'future',
    live: false,
  },
  {
    id: 'antimatter_cannon',
    name: 'ANTIMATTER CANNON',
    desc: 'Catastrophic payload weapon for top-tier destruction.',
    emoji: '☄️',
    rarity: 'legendary',
    tier: 'legendary',
    category: 'weapon',
    cost: 2000,
    usd: 39.99,
    color: '#ff44cc',
    type: 'future',
    live: false,
  },
  {
    id: 'void_ray',
    name: 'VOID RAY',
    desc: 'Void-energy beam that shreds through lanes.',
    emoji: '🌌',
    rarity: 'legendary',
    tier: 'legendary',
    category: 'weapon',
    cost: 1800,
    usd: 34.99,
    color: '#9966ff',
    type: 'future',
    live: false,
  },
  {
    id: 'black_hole_generator',
    name: 'BLACK HOLE GENERATOR',
    desc: 'Creates a singularity that consumes nearby threats.',
    emoji: '🕳️',
    rarity: 'legendary',
    tier: 'legendary',
    category: 'weapon',
    cost: 2000,
    usd: 39.99,
    color: '#5544ff',
    type: 'future',
    live: false,
  },
  {
    id: 'time_freeze_gun',
    name: 'TIME FREEZE GUN',
    desc: 'Temporarily locks the battlefield in stasis.',
    emoji: '⏱️',
    rarity: 'legendary',
    tier: 'legendary',
    category: 'weapon',
    cost: 1800,
    usd: 34.99,
    color: '#ccffff',
    type: 'future',
    live: false,
  },
  {
    id: 'portal_gun',
    name: 'PORTAL GUN',
    desc: 'Spatial portal tech creates impossible attack angles.',
    emoji: '🌀',
    rarity: 'mythic',
    tier: 'mythic',
    category: 'weapon',
    cost: 2500,
    usd: 49.99,
    color: '#66ffff',
    type: 'future',
    live: false,
  },
  {
    id: 'chaos_cannon',
    name: 'CHAOS CANNON',
    desc: 'Unstable high-tier cannon with extreme battlefield effects.',
    emoji: '🎇',
    rarity: 'mythic',
    tier: 'mythic',
    category: 'weapon',
    cost: 2500,
    usd: 49.99,
    color: '#ff6699',
    type: 'future',
    live: false,
  },
  {
    id: 'nuclear_charge',
    name: 'NUCLEAR CHARGE',
    desc: 'Endgame payload weapon for full-screen devastation.',
    emoji: '☢️',
    rarity: 'mythic',
    tier: 'mythic',
    category: 'weapon',
    cost: 2500,
    usd: 49.99,
    color: '#ffee55',
    type: 'future',
    live: false,
  },
];

// ───────────────────────────────────────────────────────────────────────────────
// UPGRADES
// Keep currently-used ids intact for gameplay compatibility.
// Existing GameCanvas specifically checks shield1, shield2, and tunnelbomb.
// ───────────────────────────────────────────────────────────────────────────────

export const UPGRADES = [
  // ===== CURRENT LIVE UPGRADES =====
  {
    id: 'shield1',
    name: 'SHIELD MK-I',
    desc: 'Absorbs 1 hit from tunnel walls or borders. Consumable — equip before each run.',
    emoji: '🛡️',
    rarity: 'starter',
    tier: 'starter',
    category: 'upgrade',
    cost: 250,
    usd: 5.99,
    type: 'shield',
    level: 1,
    hits: 1,
    killsEnemies: false,
    duration: null,
    stackable: true,
    live: true,
  },
  {
    id: 'shield2',
    name: 'SHIELD MK-II',
    desc: 'Absorbs 3 hits and destroys enemies on contact for a limited duration.',
    emoji: '💎',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'upgrade',
    cost: 1000,
    usd: 19.99,
    type: 'shield',
    level: 2,
    hits: 3,
    killsEnemies: true,
    duration: 7200,
    stackable: true,
    live: true,
  },
  {
    id: 'tunnelbomb',
    name: 'TUNNEL BOMB',
    desc: 'Widens all tunnel gaps for a limited time.',
    emoji: '💣',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'upgrade',
    cost: 1000,
    usd: 19.99,
    type: 'tunnelbomb',
    duration: 3600,
    stackable: true,
    live: true,
  },

  // ===== NEW PERMANENT UPGRADE CATALOG =====
  {
    id: 'armor_mk1',
    name: 'ARMOR MK I',
    desc: 'Permanent survivability increase.',
    emoji: '🛡️',
    rarity: 'common',
    tier: 'common',
    category: 'upgrade',
    cost: 300,
    usd: 5.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'armor_mk2',
    name: 'ARMOR MK II',
    desc: 'Improved armor plating for stronger protection.',
    emoji: '🛡️',
    rarity: 'rare',
    tier: 'rare',
    category: 'upgrade',
    cost: 600,
    usd: 11.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'armor_mk3',
    name: 'ARMOR MK III',
    desc: 'Top-tier armor upgrade for heavy endurance.',
    emoji: '🛡️',
    rarity: 'elite',
    tier: 'elite',
    category: 'upgrade',
    cost: 1000,
    usd: 19.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'shield_generator',
    name: 'SHIELD GENERATOR',
    desc: 'Permanent shield tech enhancement.',
    emoji: '🔷',
    rarity: 'rare',
    tier: 'rare',
    category: 'upgrade',
    cost: 500,
    usd: 9.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'advanced_shield_core',
    name: 'ADVANCED SHIELD CORE',
    desc: 'High-grade shield core for stronger sustained defense.',
    emoji: '💠',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'upgrade',
    cost: 900,
    usd: 17.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'damage_boost_mk1',
    name: 'DAMAGE BOOST MK I',
    desc: 'Permanent base damage increase.',
    emoji: '⚔️',
    rarity: 'common',
    tier: 'common',
    category: 'upgrade',
    cost: 300,
    usd: 5.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'damage_boost_mk2',
    name: 'DAMAGE BOOST MK II',
    desc: 'Stronger permanent damage output.',
    emoji: '⚔️',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'upgrade',
    cost: 700,
    usd: 13.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'damage_boost_mk3',
    name: 'DAMAGE BOOST MK III',
    desc: 'Top-tier permanent damage increase.',
    emoji: '⚔️',
    rarity: 'elite',
    tier: 'elite',
    category: 'upgrade',
    cost: 1200,
    usd: 21.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'fire_rate_enhancer',
    name: 'FIRE RATE ENHANCER',
    desc: 'Improves your weapon firing cadence.',
    emoji: '⚡',
    rarity: 'rare',
    tier: 'rare',
    category: 'upgrade',
    cost: 500,
    usd: 9.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'engine_boost_mk1',
    name: 'ENGINE BOOST MK I',
    desc: 'Permanent engine performance increase.',
    emoji: '🚀',
    rarity: 'common',
    tier: 'common',
    category: 'upgrade',
    cost: 300,
    usd: 5.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'engine_boost_mk2',
    name: 'ENGINE BOOST MK II',
    desc: 'Stronger speed and response upgrade.',
    emoji: '🚀',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'upgrade',
    cost: 700,
    usd: 13.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'engine_boost_mk3',
    name: 'ENGINE BOOST MK III',
    desc: 'High-end engine tuning for max mobility.',
    emoji: '🚀',
    rarity: 'elite',
    tier: 'elite',
    category: 'upgrade',
    cost: 1200,
    usd: 21.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'maneuver_thrusters',
    name: 'MANEUVER THRUSTERS',
    desc: 'Improves turning and movement control.',
    emoji: '🛞',
    rarity: 'rare',
    tier: 'rare',
    category: 'upgrade',
    cost: 500,
    usd: 9.99,
    type: 'passive',
    stackable: false,
    live: false,
  },
  {
    id: 'orbital_drone_mk1',
    name: 'ORBITAL DRONE MK I',
    desc: 'Basic orbital support drone system.',
    emoji: '🛰️',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'upgrade',
    cost: 600,
    usd: 11.99,
    type: 'orbital',
    stackable: false,
    live: false,
  },
  {
    id: 'orbital_drone_mk2',
    name: 'ORBITAL DRONE MK II',
    desc: 'Improved orbital support drone system.',
    emoji: '🛰️',
    rarity: 'elite',
    tier: 'elite',
    category: 'upgrade',
    cost: 1000,
    usd: 19.99,
    type: 'orbital',
    stackable: false,
    live: false,
  },
  {
    id: 'orbital_drone_mk3',
    name: 'ORBITAL DRONE MK III',
    desc: 'Advanced orbital drone package.',
    emoji: '🛰️',
    rarity: 'legendary',
    tier: 'legendary',
    category: 'upgrade',
    cost: 1500,
    usd: 29.99,
    type: 'orbital',
    stackable: false,
    live: false,
  },
  {
    id: 'energy_orbs_mk1',
    name: 'ENERGY ORBS MK I',
    desc: 'Basic orbiting energy orb system.',
    emoji: '🪐',
    rarity: 'advanced',
    tier: 'advanced',
    category: 'upgrade',
    cost: 700,
    usd: 13.99,
    type: 'orbital',
    stackable: false,
    live: false,
  },
  {
    id: 'energy_orbs_mk2',
    name: 'ENERGY ORBS MK II',
    desc: 'Improved orbiting orb support.',
    emoji: '🪐',
    rarity: 'elite',
    tier: 'elite',
    category: 'upgrade',
    cost: 1100,
    usd: 19.99,
    type: 'orbital',
    stackable: false,
    live: false,
  },
  {
    id: 'energy_orbs_mk3',
    name: 'ENERGY ORBS MK III',
    desc: 'Top-tier orbiting energy system.',
    emoji: '🪐',
    rarity: 'legendary',
    tier: 'legendary',
    category: 'upgrade',
    cost: 1600,
    usd: 29.99,
    type: 'orbital',
    stackable: false,
    live: false,
  },
];

// ───────────────────────────────────────────────────────────────────────────────
// SPECIALS
// Consumables / repeat-buy items
// ───────────────────────────────────────────────────────────────────────────────

export const SPECIALS = [
  {
    id: 'teleport_blink',
    name: 'TELEPORT BLINK',
    desc: 'Short-range emergency repositioning burst.',
    emoji: '🌀',
    rarity: 'common',
    tier: 'escape',
    category: 'special',
    subgroup: 'escape',
    uses: 3,
    cost: 300,
    usd: 5.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'phase_shift',
    name: 'PHASE SHIFT',
    desc: 'Phase through danger for a brief moment.',
    emoji: '👻',
    rarity: 'common',
    tier: 'escape',
    category: 'special',
    subgroup: 'escape',
    uses: 2,
    cost: 250,
    usd: 4.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'time_freeze_special',
    name: 'TIME FREEZE',
    desc: 'Freezes battlefield motion for a short window.',
    emoji: '⏱️',
    rarity: 'rare',
    tier: 'escape',
    category: 'special',
    subgroup: 'escape',
    uses: 2,
    cost: 400,
    usd: 7.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'emergency_warp',
    name: 'EMERGENCY WARP',
    desc: 'Last-second warp to escape certain destruction.',
    emoji: '🌠',
    rarity: 'rare',
    tier: 'escape',
    category: 'special',
    subgroup: 'escape',
    uses: 1,
    cost: 500,
    usd: 9.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'reverse_time',
    name: 'REVERSE TIME',
    desc: 'Rewinds recent danger and recovers your position.',
    emoji: '↩️',
    rarity: 'rare',
    tier: 'escape',
    category: 'special',
    subgroup: 'escape',
    uses: 2,
    cost: 450,
    usd: 8.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'energy_shield_dome',
    name: 'ENERGY SHIELD DOME',
    desc: 'Temporary dome-style damage protection.',
    emoji: '🛡️',
    rarity: 'common',
    tier: 'defense',
    category: 'special',
    subgroup: 'defense',
    uses: 1,
    cost: 300,
    usd: 5.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'damage_nullifier',
    name: 'DAMAGE NULLIFIER',
    desc: 'Cancels incoming damage for a limited duration.',
    emoji: '🚫',
    rarity: 'rare',
    tier: 'defense',
    category: 'special',
    subgroup: 'defense',
    uses: 1,
    cost: 350,
    usd: 6.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'drone_shield',
    name: 'DRONE SHIELD',
    desc: 'Deploys defensive drones around your craft.',
    emoji: '🛸',
    rarity: 'rare',
    tier: 'defense',
    category: 'special',
    subgroup: 'defense',
    uses: 1,
    cost: 400,
    usd: 7.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'last_stand_mode',
    name: 'LAST STAND MODE',
    desc: 'Emergency survival mode when things go bad.',
    emoji: '❤️',
    rarity: 'rare',
    tier: 'defense',
    category: 'special',
    subgroup: 'defense',
    uses: 1,
    cost: 500,
    usd: 9.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'screen_nuke',
    name: 'SCREEN NUKE',
    desc: 'Wipes the battlefield in one devastating blast.',
    emoji: '☢️',
    rarity: 'rare',
    tier: 'offense',
    category: 'special',
    subgroup: 'offense',
    uses: 1,
    cost: 500,
    usd: 9.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'missile_barrage',
    name: 'MISSILE BARRAGE',
    desc: 'Launches a heavy wave of homing missiles.',
    emoji: '🚀',
    rarity: 'rare',
    tier: 'offense',
    category: 'special',
    subgroup: 'offense',
    uses: 1,
    cost: 400,
    usd: 7.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'chain_lightning_storm',
    name: 'CHAIN LIGHTNING STORM',
    desc: 'Unleashes chained electric strikes across targets.',
    emoji: '⚡',
    rarity: 'rare',
    tier: 'offense',
    category: 'special',
    subgroup: 'offense',
    uses: 1,
    cost: 350,
    usd: 6.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'sonic_boom',
    name: 'SONIC BOOM',
    desc: 'Clears pressure with a concussive burst.',
    emoji: '🌊',
    rarity: 'common',
    tier: 'offense',
    category: 'special',
    subgroup: 'offense',
    uses: 1,
    cost: 200,
    usd: 3.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'auto_pilot',
    name: 'AUTO-PILOT',
    desc: 'Temporary auto-guidance support.',
    emoji: '🤖',
    rarity: 'advanced',
    tier: 'utility',
    category: 'special',
    subgroup: 'utility',
    uses: 1,
    cost: 600,
    usd: 11.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'coin_multiplier',
    name: 'COIN MULTIPLIER',
    desc: 'Boosts coin gains for a limited time.',
    emoji: '🪙',
    rarity: 'rare',
    tier: 'utility',
    category: 'special',
    subgroup: 'utility',
    uses: 1,
    cost: 500,
    usd: 9.99,
    repeatable: true,
    live: false,
  },
  {
    id: 'cooldown_reset',
    name: 'COOLDOWN RESET',
    desc: 'Instantly refreshes active cooldowns.',
    emoji: '🔄',
    rarity: 'common',
    tier: 'utility',
    category: 'special',
    subgroup: 'utility',
    uses: 1,
    cost: 300,
    usd: 5.99,
    repeatable: true,
    live: false,
  },
];

// ───────────────────────────────────────────────────────────────────────────────
// COMBO PACKS
// One-time by default unless repeatable is set true
// ───────────────────────────────────────────────────────────────────────────────

export const COMBO_PACKS = [
  {
    id: 'starter_combo',
    name: 'STARTER COMBO',
    desc: 'Solid early bundle for new pilots.',
    emoji: '💥',
    category: 'combo',
    cost: 900,
    usd: 12.99,
    valueUsd: 17.99,
    repeatable: false,
    live: false,
    contents: [
      { category: 'weapon', id: 'pulse_rifle', qty: 1 },
      { category: 'upgrade', id: 'armor_mk1', qty: 1 },
      { category: 'special', id: 'teleport_blink', qty: 1 },
    ],
  },
  {
    id: 'speed_combo',
    name: 'SPEED COMBO',
    desc: 'Movement-first package for aggressive pilots.',
    emoji: '⚡',
    category: 'combo',
    cost: 1600,
    usd: 19.99,
    valueUsd: 29.99,
    repeatable: false,
    live: false,
    contents: [
      { category: 'skin', id: 'neon_phantom', qty: 1 },
      { category: 'upgrade', id: 'engine_boost_mk2', qty: 1 },
      { category: 'special', id: 'auto_pilot', qty: 1 },
    ],
  },
  {
    id: 'destruction_combo',
    name: 'DESTRUCTION COMBO',
    desc: 'High-damage bundle for heavy offense.',
    emoji: '💣',
    category: 'combo',
    cost: 2000,
    usd: 29.99,
    valueUsd: 39.99,
    repeatable: false,
    live: false,
    contents: [
      { category: 'weapon', id: 'seismic_cannon', qty: 1 },
      { category: 'upgrade', id: 'damage_boost_mk2', qty: 1 },
      { category: 'special', id: 'missile_barrage', qty: 1 },
    ],
  },
  {
    id: 'defense_combo',
    name: 'DEFENSE COMBO',
    desc: 'Protective bundle for survivability-focused play.',
    emoji: '🛡️',
    category: 'combo',
    cost: 1500,
    usd: 19.99,
    valueUsd: 29.99,
    repeatable: false,
    live: false,
    contents: [
      { category: 'upgrade', id: 'shield_generator', qty: 1 },
      { category: 'special', id: 'drone_shield', qty: 1 },
      { category: 'upgrade', id: 'armor_mk2', qty: 1 },
    ],
  },
  {
    id: 'orbital_combo',
    name: 'ORBITAL COMBO',
    desc: 'Fan-favorite orbital support package.',
    emoji: '🛰️',
    category: 'combo',
    cost: 1800,
    usd: 24.99,
    valueUsd: 34.99,
    repeatable: false,
    live: false,
    contents: [
      { category: 'upgrade', id: 'orbital_drone_mk2', qty: 1 },
      { category: 'upgrade', id: 'energy_orbs_mk1', qty: 1 },
      { category: 'upgrade', id: 'damage_boost_mk1', qty: 1 },
    ],
  },
];

// ───────────────────────────────────────────────────────────────────────────────
// VEHICLES (future-proof / optional)
// For now you can keep using skins visually and add vehicle logic later.
// ───────────────────────────────────────────────────────────────────────────────

export const VEHICLES = [
  {
    id: 'default_jet',
    name: 'DEFAULT JET',
    desc: 'Standard FirePilot frame.',
    emoji: '✈️',
    category: 'vehicle',
    cost: 0,
    usd: 0,
    live: true,
  },
];

// ───────────────────────────────────────────────────────────────────────────────
// CATALOG HELPERS
// ───────────────────────────────────────────────────────────────────────────────

export function getWeapon(id) {
  return WEAPONS.find((w) => w.id === id) || WEAPONS[0];
}

export function getUpgrade(id) {
  return UPGRADES.find((u) => u.id === id) || null;
}

export function getSpecial(id) {
  return SPECIALS.find((s) => s.id === id) || null;
}

export function getComboPack(id) {
  return COMBO_PACKS.find((c) => c.id === id) || null;
}

export function getVehicle(id) {
  return VEHICLES.find((v) => v.id === id) || VEHICLES[0];
}

export function getLiveWeapons() {
  return WEAPONS.filter((item) => item.live);
}

export function getLiveUpgrades() {
  return UPGRADES.filter((item) => item.live);
}

export function getLiveSpecials() {
  return SPECIALS.filter((item) => item.live);
}

export function getLiveComboPacks() {
  return COMBO_PACKS.filter((item) => item.live);
}

export function getItemsByCategory(category) {
  switch (category) {
    case 'weapons':
      return WEAPONS;
    case 'upgrades':
      return UPGRADES;
    case 'specials':
      return SPECIALS;
    case 'combos':
      return COMBO_PACKS;
    case 'vehicles':
      return VEHICLES;
    default:
      return [];
  }
}
